sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/model-storage
    - IMAGE_TAG=${TRAVIS_BRANCH}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup
  - make databases

script:
  - make flake8
  - make isort
  - make license
  - make safety
  - make test-travis

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "Yy3wkJPBYWglJLoouq8E5IpYgROICSWdt45bd0Yjkra09EBAAbfF1iZPUYiIugGTEiGvqKN9mQpHdM/NNqvnQuy9ctJKqpMzH4qIUhw0MgX2ahLN/q0hjHeCwjKf9Mwqcl2tCmIJA0rLNtAPAvd0qCyKmkkYmwYd8p0TXdk4zgFMhDPznCdPhZ7SF9uE4soG5OrhnnY9AeadH+JF4nZs8JgQwYZ9MgPcQjyVCs7cs1u37+iYNSrlOWQOJa2jvYdlNDWa7TRb6/3LUgNZJ6o6oGgEvt77SqUhg5sMjhvtDBN1qcG8QzgGxx3Rp6BFpVY1hJDmt1Eb1CyXEDu4FRld29pbG+pVr6RaJJ/IfFIojYTjf/ijfzVIjkSiM5tCVEmBs037M0n4uqvWZqMmqJiEKMqqLC3VqacphTPSjXiZR5DBLUyttdJj/KfwmXeGgpmZOc8N/EgYzhOhSqQ4x735tF2b1UikUQhMBqNbpnCz5pW+4l+Av0PBwFG+A9waoaAVnioZk2GxoFHwNd/YQweovrM2mjabMINcClgSmo0SqC2IodEiAsPbVHV+HirnNRC4D9fmfE8VuMDQvk3JZaiHSXPVWMXXywnILs+fOgrXd433fjL32woqz8NDhROJLmaHoQZ8fmuDWdnlCpZW1ZNkVU+bcNBnRSgMHwmblVjcKMk="
    on_success: change
    on_failure: change
    on_pull_requests: false
