os: linux
language: shell

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
- docker

env:
  global:
  - IMAGE=gcr.io/dd-decaf-cfbf6/model-storage
  - BRANCH=${TRAVIS_BRANCH}
  - BUILD_COMMIT=${TRAVIS_COMMIT}
  - SHORT_COMMIT=${TRAVIS_COMMIT:0:7}
  - BUILD_DATE=$(date -u +%Y-%m-%d)
  - BUILD_TAG=${BRANCH}_${BUILD_DATE}_${SHORT_COMMIT}
  - POSTGRES_PASS=secret

before_install:
- ./scripts/install_gcloud.sh
- ./scripts/install_kubectl.sh
- make setup

install:
- make build
- make build-travis
- make post-build
- make start

script:
- make style
- make safety
# Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
- docker-compose exec -e ENVIRONMENT=testing web pytest --cov=model_storage --cov-report=term --cov-report=xml
- bash <(curl -s https://codecov.io/bash)

before_deploy:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then make push; fi

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      secure: "Yy3wkJPBYWglJLoouq8E5IpYgROICSWdt45bd0Yjkra09EBAAbfF1iZPUYiIugGTEiGvqKN9mQpHdM/NNqvnQuy9ctJKqpMzH4qIUhw0MgX2ahLN/q0hjHeCwjKf9Mwqcl2tCmIJA0rLNtAPAvd0qCyKmkkYmwYd8p0TXdk4zgFMhDPznCdPhZ7SF9uE4soG5OrhnnY9AeadH+JF4nZs8JgQwYZ9MgPcQjyVCs7cs1u37+iYNSrlOWQOJa2jvYdlNDWa7TRb6/3LUgNZJ6o6oGgEvt77SqUhg5sMjhvtDBN1qcG8QzgGxx3Rp6BFpVY1hJDmt1Eb1CyXEDu4FRld29pbG+pVr6RaJJ/IfFIojYTjf/ijfzVIjkSiM5tCVEmBs037M0n4uqvWZqMmqJiEKMqqLC3VqacphTPSjXiZR5DBLUyttdJj/KfwmXeGgpmZOc8N/EgYzhOhSqQ4x735tF2b1UikUQhMBqNbpnCz5pW+4l+Av0PBwFG+A9waoaAVnioZk2GxoFHwNd/YQweovrM2mjabMINcClgSmo0SqC2IodEiAsPbVHV+HirnNRC4D9fmfE8VuMDQvk3JZaiHSXPVWMXXywnILs+fOgrXd433fjL32woqz8NDhROJLmaHoQZ8fmuDWdnlCpZW1ZNkVU+bcNBnRSgMHwmblVjcKMk="
    on_success: change
    on_failure: change
    on_pull_requests: false
