version: "3.1"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/model-storage:${IMAGE_TAG:-latest}
    depends_on:
      - postgres
    networks:
      default:
      DD-DeCaF:
        aliases:
          - model_storage
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/model_storage/wsgi.py
      - SCRIPT_NAME=${SCRIPT_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME:-model_storage}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - IAM_API=https://api-staging.dd-decaf.eu/iam
    command: gunicorn -c gunicorn.py model_storage.wsgi:app

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default

networks:
  DD-DeCaF:
    external: true
