version: "3.1"
services:
  web:
    user: giraffe
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/dd-decaf-cfbf6/model_warehouse:${IMAGE_TAG:-latest}
    networks:
      default:
      DD-DeCaF:
        aliases:
          - model_warehouse
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ".:/app"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - FLASK_APP=src/model_warehouse/wsgi.py
      - SCRIPT_NAME=${SCRIPT_NAME}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:4200}
      - SENTRY_DSN=${SENTRY_DSN}
    command: gunicorn -c gunicorn.py model_warehouse.wsgi:app

# Additional services that the `web` service `depends_on` should usually only
# be on the default network and not exposed on the general network, i.e.,
# networks:
#   - default

networks:
  DD-DeCaF:
    external: true
