apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-storage-production
spec:
  selector:
    matchLabels:
      app: model-storage
      env: production
  replicas: 1
  template:
    metadata:
      labels:
        app: model-storage
        env: production
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/model-storage:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: production
        - name: SCRIPT_NAME
          value: /mstorage
        - name: FLASK_APP
          value: src/model_storage/wsgi.py
        - name: ALLOWED_ORIGINS
          value: https://app.dd-decaf.eu,http://localhost:4200
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: model-storage-production
              key: SENTRY_DSN
        command: ["gunicorn", "-c", "gunicorn.py", "model_storage.wsgi:app"]
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "100m"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "-instances=dd-decaf-cfbf6:europe-west1:dd-decaf=tcp:5432", "-credential_file=/secrets/cloudsql/credentials.json"]
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "100m"
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-storage-staging
spec:
  selector:
    matchLabels:
      app: model-storage
      env: staging
  replicas: 1
  template:
    metadata:
      labels:
        app: model-storage
        env: staging
    spec:
      containers:
      - name: web
        image: gcr.io/dd-decaf-cfbf6/model-storage:devel
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: staging
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: model-storage-staging
              key: SECRET_KEY
        - name: SCRIPT_NAME
          value: /mstorage
        - name: FLASK_APP
          value: src/model_storage/wsgi.py
        - name: ALLOWED_ORIGINS
          value: https://caffeine.dd-decaf.eu,http://localhost:4200
        - name: POSTGRES_HOST
          value: localhost
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB_NAME
          value: model_storage_staging
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: model-storage-staging
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: model-storage-staging
              key: POSTGRES_PASS
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: model-storage-staging
              key: SENTRY_DSN
        - name: IAM_API
          value: "http://iam-staging/iam"
        command: ["gunicorn", "-c", "gunicorn.py", "model_storage.wsgi:app"]
        resources:
          requests:
            cpu: "5m"
          limits:
            cpu: "100m"
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy", "-instances=dd-decaf-cfbf6:europe-west1:dd-decaf=tcp:5432", "-credential_file=/secrets/cloudsql/credentials.json"]
        resources:
          requests:
            cpu: "5m"
          limits:
            cpu: "100m"
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials
