"""empty message

Revision ID: 2538b67922e2
Revises: 19c7012eceb0
Create Date: 2019-10-14 08:51:11.398595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2538b67922e2'
down_revision = '19c7012eceb0'
branch_labels = None
depends_on = None


def upgrade():
    # Create the column with nullable=True, update existing rows with False
    # value, then reset nullable to False.
    op.add_column('model', sa.Column('ec_model', sa.Boolean(), nullable=True))
    model = sa.sql.table('model', sa.sql.column('ec_model'))
    op.execute(model.update().values(ec_model=False))
    op.alter_column('model', 'ec_model', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'ec_model')
    # ### end Alembic commands ###
