"""empty message

Revision ID: ebda05acce73
Revises: 1a664fb50066
Create Date: 2018-09-04 13:13:57.336362

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ebda05acce73'
down_revision = '1a664fb50066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'model_serialized')
    op.add_column('model', sa.Column('model_serialized', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'model_serialized')
    op.add_column('model', sa.Column('model_serialized', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
