"""integer organism identifiers

Revision ID: f55ed1a98c68
Revises: ebda05acce73
Create Date: 2018-10-23 10:19:38.581047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55ed1a98c68'
down_revision = 'ebda05acce73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'organism_id', existing_type=sa.String(256),
                    type_=sa.Integer(), postgresql_using="organism_id::integer")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'organism_id', existing_type=sa.Integer(),
                    type_=sa.String(256))
    # ### end Alembic commands ###
